
baseurl: "/"
title: 'A History of Cesar Chavez'
defaultContentLanguage: en
languages:
  en:
    lang: en
    languageName: English
    weight: 0
staticDir: static
MetaDataFormat: 'yaml'
theme: 'history'
